drop database Events;
create database Events;

CREATE TABLE Users (
	UID SERIAL PRIMARY KEY,
	email VARCHAR(30) UNIQUE NOT NULL,
	name VARCHAR(30) NOT NULL,
	hash VARCHAR(512) NOT NULL,
	salt VARCHAR(512) NOT NULL
);

CREATE TABLE Admins (
	UID SERIAL PRIMARY KEY,
	FOREIGN KEY (UID) REFERENCES Users(UID)
		ON DELETE CASCADE
);

CREATE TABLE SuperAdmins (
	UID SERIAL PRIMARY KEY,
	FOREIGN KEY (UID) REFERENCES Users(UID)
		ON DELETE CASCADE
);

CREATE TABLE Events (
	EID SERIAL PRIMARY KEY,
	email VARCHAR(30) NOT NULL,
	name VARCHAR(88) NOT NULL,
	description VARCHAR(88),
	phone VARCHAR(20),
	datestamp DATE
);

CREATE TABLE Events_Private (
	EID SERIAL PRIMARY KEY,
	FOREIGN KEY (EID) REFERENCES Events(EID)
		ON DELETE CASCADE
);

CREATE TABLE RSOs (
	RID SERIAL PRIMARY KEY,
	name VARCHAR(88)
);

CREATE TABLE Events_RSO (
	EID SERIAL PRIMARY KEY,
	RID INTEGER,
	FOREIGN KEY (EID) REFERENCES Events(EID)
		ON DELETE CASCADE,
	FOREIGN KEY (RID) REFERENCES RSOs(RID)
		ON DELETE CASCADE
);

CREATE TABLE Comments (
	CID SERIAL PRIMARY KEY,
	email VARCHAR(30),
	text VARCHAR(88),
	honor INTEGER,
	EID INTEGER NOT NULL,
	datestamp DATE,
	FOREIGN KEY (EID) REFERENCES Events(EID)
		ON DELETE CASCADE
);

CREATE TABLE Universities (
	UNID SERIAL PRIMARY KEY,
	num_students INTEGER,
	name VARCHAR(88),
	description VARCHAR(200)
);

CREATE TABLE Universities_Pictures (
	UNID SERIAL,
	file_path VARCHAR(50) PRIMARY KEY,
	FOREIGN KEY (UNID) REFERENCES Universities(UNID)
		ON DELETE CASCADE
);
